name: flutter_runtime_ide
version: 0.2.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  file_picker: ^5.3.0
  path: ^1.8.2
  shared_preferences: ^2.1.1
  darty_json_safe: ^1.0.1
  # darty_json_safe:
  #   path: packages/darty_json
  analyzer: ^5.13.0
  loading_indicator: ^3.1.1
  mustache_template: ^2.0.0
  process_run: ^0.13.0
  liquid_progress_indicator: ^0.4.0
  logger: ^1.3.0
  pubspec_parse: ^1.2.3
  crypto: ^3.0.3
  scrollable_positioned_list: ^0.3.8
  menu_button: ^1.4.2
  fuzzywuzzy: 1.1.2
  flutter:
    sdk: flutter
  # flutter_runtime_center:
  #   path: .runtime/
  event_bus: ^2.0.0
  flutter_expanded_tile: ^0.3.7
  dcm:
    git:
      url: https://github.com/josercc/dcm.git
      ref: 1.3.0
  analyze_cache:
    git:
      url: https://github.com/flutter-runtime/analyze_cache.git
      ref: main
  pubspec_yaml: ^3.1.0
  markdown_widget: ^2.2.0
  plugin_channel:
    git:
      url: https://github.com/flutter-runtime/plugin_channel.git
      ref: main

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  process_run: 0.13.0
# analyzer:
#   path: /Users/king/.pub-cache/hosted/pub.flutter-io.cn/analyzer-5.13.0

flutter:
  uses-material-design: true
