name: flutter_runtime_ide
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  file_picker: ^5.3.0
  path: ^1.8.2
  shared_preferences: ^2.1.1
  darty_json_safe: ^1.0.1
  analyzer: ^5.13.0
  mustache_template: ^2.0.0
  process_run: ^0.13.0
  liquid_progress_indicator: ^0.4.0
  logger: ^1.3.0
  pubspec_parse: ^1.2.3
  crypto: ^3.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
