name: flutter_runtime_center
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  _fe_analyzer_shared_runtime:
    path: /Users/king/.runtime/_fe_analyzer_shared-61.0.0
  analyzer_runtime:
    path: /Users/king/.runtime/analyzer-5.13.0
  args_runtime:
    path: /Users/king/.runtime/args-2.4.1
  async_runtime:
    path: /Users/king/.runtime/async-2.10.0
  boolean_selector_runtime:
    path: /Users/king/.runtime/boolean_selector-2.1.1
  characters_runtime:
    path: /Users/king/.runtime/characters-1.2.1
  charcode_runtime:
    path: /Users/king/.runtime/charcode-1.3.1
  checked_yaml_runtime:
    path: /Users/king/.runtime/checked_yaml-2.0.3
  clock_runtime:
    path: /Users/king/.runtime/clock-1.1.1
  collection_runtime:
    path: /Users/king/.runtime/collection-1.17.0
  convert_runtime:
    path: /Users/king/.runtime/convert-3.1.1
  crypto_runtime:
    path: /Users/king/.runtime/crypto-3.0.3
  cupertino_icons_runtime:
    path: /Users/king/.runtime/cupertino_icons-1.0.5
  darty_json_safe_runtime:
    path: /Users/king/.runtime/darty_json_safe-1.0.1
  fake_async_runtime:
    path: /Users/king/.runtime/fake_async-1.3.1
  ffi_runtime:
    path: /Users/king/.runtime/ffi-2.0.2
  file_runtime:
    path: /Users/king/.runtime/file-6.1.4
  file_picker_runtime:
    path: /Users/king/.runtime/file_picker-5.3.0
  # flutter_runtime:
  #   path: /Users/king/.runtime/flutter
  flutter_lints_runtime:
    path: /Users/king/.runtime/flutter_lints-2.0.1
  flutter_plugin_android_lifecycle_runtime:
    path: /Users/king/.runtime/flutter_plugin_android_lifecycle-2.0.14
  # flutter_test_runtime:
  #   path: /Users/king/.runtime/flutter_test
  flutter_web_plugins_runtime:
    path: /Users/king/.runtime/flutter_web_plugins
  fuzzywuzzy_runtime:
    path: /Users/king/.runtime/fuzzywuzzy-1.1.2
  get_runtime:
    path: /Users/king/.runtime/get-4.6.5
  glob_runtime:
    path: /Users/king/.runtime/glob-2.1.2
  js_runtime:
    path: /Users/king/.runtime/js-0.6.5
  json_annotation_runtime:
    path: /Users/king/.runtime/json_annotation-4.8.1
  lints_runtime:
    path: /Users/king/.runtime/lints-2.0.1
  liquid_progress_indicator_runtime:
    path: /Users/king/.runtime/liquid_progress_indicator-0.4.0
  loading_indicator_runtime:
    path: /Users/king/.runtime/loading_indicator-3.1.1
  logger_runtime:
    path: /Users/king/.runtime/logger-1.3.0
  matcher_runtime:
    path: /Users/king/.runtime/matcher-0.12.13
  material_color_utilities_runtime:
    path: /Users/king/.runtime/material_color_utilities-0.2.0
  menu_button_runtime:
    path: /Users/king/.runtime/menu_button-1.4.2+1
  meta_runtime:
    path: /Users/king/.runtime/meta-1.8.0
  mustache_template_runtime:
    path: /Users/king/.runtime/mustache_template-2.0.0
  package_config_runtime:
    path: /Users/king/.runtime/package_config-2.1.0
  path_runtime:
    path: /Users/king/.runtime/path-1.8.2
  path_provider_linux_runtime:
    path: /Users/king/.runtime/path_provider_linux-2.1.10
  path_provider_platform_interface_runtime:
    path: /Users/king/.runtime/path_provider_platform_interface-2.0.6
  path_provider_windows_runtime:
    path: /Users/king/.runtime/path_provider_windows-2.1.6
  platform_runtime:
    path: /Users/king/.runtime/platform-3.1.0
  plugin_platform_interface_runtime:
    path: /Users/king/.runtime/plugin_platform_interface-2.1.4
  process_runtime:
    path: /Users/king/.runtime/process-4.2.4
  process_run_runtime:
    path: /Users/king/.runtime/process_run-0.13.0
  pub_semver_runtime:
    path: /Users/king/.runtime/pub_semver-2.1.4
  pubspec_parse_runtime:
    path: /Users/king/.runtime/pubspec_parse-1.2.3
  scrollable_positioned_list_runtime:
    path: /Users/king/.runtime/scrollable_positioned_list-0.3.8
  shared_preferences_runtime:
    path: /Users/king/.runtime/shared_preferences-2.1.1
  shared_preferences_android_runtime:
    path: /Users/king/.runtime/shared_preferences_android-2.1.4
  shared_preferences_foundation_runtime:
    path: /Users/king/.runtime/shared_preferences_foundation-2.2.2
  shared_preferences_linux_runtime:
    path: /Users/king/.runtime/shared_preferences_linux-2.2.0
  shared_preferences_platform_interface_runtime:
    path: /Users/king/.runtime/shared_preferences_platform_interface-2.2.0
  shared_preferences_web_runtime:
    path: /Users/king/.runtime/shared_preferences_web-2.1.0
  shared_preferences_windows_runtime:
    path: /Users/king/.runtime/shared_preferences_windows-2.2.0
  sky_engine_runtime:
    path: /Users/king/.runtime/sky_engine
  source_span_runtime:
    path: /Users/king/.runtime/source_span-1.9.1
  stack_trace_runtime:
    path: /Users/king/.runtime/stack_trace-1.11.0
  stream_channel_runtime:
    path: /Users/king/.runtime/stream_channel-2.1.1
  string_scanner_runtime:
    path: /Users/king/.runtime/string_scanner-1.2.0
  synchronized_runtime:
    path: /Users/king/.runtime/synchronized-3.1.0
  term_glyph_runtime:
    path: /Users/king/.runtime/term_glyph-1.2.1
  test_api_runtime:
    path: /Users/king/.runtime/test_api-0.4.16
  typed_data_runtime:
    path: /Users/king/.runtime/typed_data-1.3.2
  vector_math_runtime:
    path: /Users/king/.runtime/vector_math-2.1.4
  watcher_runtime:
    path: /Users/king/.runtime/watcher-1.0.2
  win32_runtime:
    path: /Users/king/.runtime/win32-4.1.4
  xdg_directories_runtime:
    path: /Users/king/.runtime/xdg_directories-1.0.0
  yaml_runtime:
    path: /Users/king/.runtime/yaml-3.1.2
  flutter_runtime_ide_runtime:
    path: /Users/king/.runtime/..
