name: "build flutter macos app"
on:
  push:
    branches:
      - main
env:
  FLUTTER_VERSION: "3.7.12"
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Flutter Version
        id: flutter_version
        uses: bungabear/flutter_version_read@main
        with:
          file: ./pubspec.yml
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.12'
      - run: flutter build macos --release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.flutter_version.outputs.version_number }}
          prerelease: true
          title: "Development Build"
          files: |
            build/macos/Release/flutter_runtime_ide.app
